name: build docs
on: push
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: dispatches
        run: |
          curl -XPOST -u "${{ secrets.REMOTE_DISPATCH }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/Bultako/GithubReactions/dispatches \
          --data '{"event_type": "build", "client_payload": { "release": "1.2.3" }}'
