name: build docs
on: push
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch validation
        run: |
          run: |
          curl -XPOST -u "${{ secrets.REMOTE_DISPATCH }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/Bultako/GithubReactions/dispatches \
          --data '{"event_type": "build", "release_number": "v0.18.2"}'
