name: build docs
on:
  release:
    types: [published]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: release
        run: |
          echo ${{ github.event.release.tag_name }}

#          curl -XPOST -u "${{ secrets.REMOTE_DISPATCH }}" \
#          -H "Accept: application/vnd.github.everest-preview+json" \
#          -H "Content-Type: application/json" https://api.github.com/repos/Bultako/GithubReactions/dispatches \
#          --data '{"event_type": "release", "client_payload": { "release": "1.2.3" }}'
