name: build docs
on:
  release:
    types: [published]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: master
      - name: modif docs
        run: |
          sed -i -E 's/gammapy-.*-environment.yml/gammapy-${{ github.event.release.tag_name }}-environment.yml/' docs/install/index.rst
          sed -i -E 's/called\s``gammapy-.*``/called ``gammapy-${{ github.event.release.tag_name }}``/' docs/install/index.rst
          sed -i -E 's/activate\sgammapy-.*/activate gammapy-${{ github.event.release.tag_name }}/' docs/install/index.rst
          sed -i -E 's/--release\s.*/--release ${{ github.event.release.tag_name }}/' docs/install/index.rst
#      - name: dispatch web
#        run: |
#          curl -XPOST -u "${{ secrets.REMOTE_DISPATCH }}" \
#          -H "Accept: application/vnd.github.everest-preview+json" \
#          -H "Content-Type: application/json" https://api.github.com/repos/Bultako/GithubReactions/dispatches \
#          --data '{"event_type": "release", "client_payload": { "release": "${{ github.event.release.tag_name }}" }}'
#      - name: dispatch docs
#        run: |
#          curl -XPOST -u "${{ secrets.REMOTE_DISPATCH }}" \
#          -H "Accept: application/vnd.github.everest-preview+json" \
#          -H "Content-Type: application/json" https://api.github.com/repos/Bultako/GithubReactions/dispatches \
#          --data '{"event_type": "release", "client_payload": { "release": "${{ github.event.release.tag_name }}" }}'
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.9.0
        with:
          branch: master
          commit_author: GitHub Actions <actions@github.com>
          commit_message: commit docs modif